### ISSUE TITLE
Edits locked while background job is running

### ISSUE THREAD

**Issue by friendly-lib** [hudmol/as_spreadsheet_bulk_updater#12]
We've noticed that when one of the “Spreadsheet Bulk Update Job” is running, all users are blocked from saving edits to any record (accession, recourse, etc.) that is linked to any top container. This is a big problem at my institution, where some users are running jobs that take over an hour to complete. 

Is it possible to stop this from happening, so that changes could be made even while the background job is running? 

Or maybe to pop up a warning message on records linked to top containers _before_ users start editing a record, so that they know they won't be able to save changes until the background job is done? 

Thank you!

**Comment by jambun** [comment]
Hi @friendly-lib,

The record lock is required to ensure data integrity - the update either works in its entirety or is completely rolled back if there is an issue.

The price we pay for this is that, as you note, all affected records are uneditable during the run.

Some work-arounds you might consider:
  - Start update jobs at the end of the day so they run while no one is trying to use the system.
  - Select smaller subsets of records for each run, so that each run is quick and targeted.

The pop up message is tricky because we don't know if a record is locked until we attempt to save it.


Cheers,
James
